const prisma = require('../config/db');
const geminiClient = require('./geminiClient');
const { searchHRDocuments } = require('./vectorSearch');
const { generateRosterPlan } = require('./rosterSimulationService');
const crypto = require('crypto');

async function runIrisAnalysis(taskId) {
  try {
    // 1. Lock and Update Task Atomically
    const updateResult = await prisma.basePrisma.irisTask.updateMany({
      where: { id: taskId, status: 'NEW' },
      data: { status: 'ANALYZING' }
    });

    if (updateResult.count === 0) {
      console.log(`Task ${taskId} is no longer in NEW state.`);
      return;
    }

    const task = await prisma.basePrisma.irisTask.findUnique({
      where: { id: taskId },
      include: { tenant: true }
    });

    const event = await prisma.basePrisma.outboxEvent.findUnique({
      where: { id: task.sourceEventId }
    });

    const { department, date } = event.payload; // Assuming payload has this
    
    // 2. Call Deterministic Engine for the Solution
    // The AI does NOT calculate the roster. The engine does.
    const { currentFingerprint, proposedFingerprint, plan, metrics } = await generateRosterPlan(task.tenantId, date, 1, department);
    
    // Inject simulation parameters so the executor can verify the fingerprint accurately
    metrics.simulationParams = { targetDate: date, daysAhead: 1, departmentFilter: department };

    // Persist the simulation so it has a planId
    const simulation = await prisma.basePrisma.rosterSimulation.create({
      data: {
        tenantId: task.tenantId,
        currentFingerprint,
        proposedFingerprint,
        plan,
        metrics,
        createdBy: 'IRIS_SYSTEM',
        expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000) // 24 hours expiry for AI tasks
      }
    });

    const planId = simulation.id;

    // 3. Evidence Builder: Gather cross-engine context for the explanation
    const proposedAssignments = plan.filter(p => p.action === 'ASSIGN');
    const employeeIds = proposedAssignments.map(p => p.employeeId);
    
    const employees = await prisma.basePrisma.user.findMany({
      where: { id: { in: employeeIds } },
      select: { id: true, displayName: true, attritionRiskScore: true }
    });

    // 4. Policy RAG
    const policyQuery = `Shift assignment overtime rest policy rules`;
    const chunks = await searchHRDocuments(policyQuery, task.tenantId, 3, 1);
    const policyDocs = chunks.map(c => `[Document: ${c.title}]\n${c.content}`).join('\n\n');

    // 5. Construct Mega Prompt
    const prompt = `
You are Iris, the Proactive Workforce Intelligence AI for Crew.
A ROSTER_SHORTAGE event was detected for the ${department} department on ${date}.
The deterministic roster engine has automatically calculated the optimal shift assignments to resolve this shortage.

Your job is NOT to calculate shifts. Your job is to EXPLAIN the engine's plan to the HR Manager using the evidence provided. 
You MUST be extremely specific, brief, and clear. Do not use generic corporate filler.

[DETERMINISTIC PLAN GENERATED BY ENGINE]
Plan ID: ${planId}
Expected Coverage: ${metrics.current.coverage}% -> ${metrics.proposed.coverage}%
New Overtime: ${metrics.proposed.overtime} hours
Assignments: ${JSON.stringify(proposedAssignments, null, 2)}

[EMPLOYEE RISK DATA]
${JSON.stringify(employees, null, 2)}

[RELEVANT POLICIES]
${policyDocs || 'No explicit policies found.'}

Analyze the deterministic plan against the employee risk data and policies.
Output a JSON recommendation adhering exactly to this schema:
{
  "type": "ROSTER_ADJUSTMENT",
  "evidence": {
    "summary": "A 1-sentence brief stating exactly what was missing and who was assigned (use real names).",
    "metrics": {
      "coverageImpact": "96%",
      "overtimeHours": 12,
      "employeesAffected": 1
    }
  },
  "recommendedAction": "Write EXACTLY 1 plain, conversational sentence explaining the human action. DO NOT mention any percentages, numbers, hours, metrics, or Plan IDs in this text because they are displayed visually elsewhere. Example: 'An unassigned Night Shift in Engineering caused a gap, so Iris has been scheduled to cover it.'",
  "actionType": "ROSTER_ADJUSTMENT",
  "actionParameters": { "planId": "${planId}" }
}

ONLY OUTPUT VALID JSON.
`;

    // 6. Call Gemini
    const ai = geminiClient.getAI();
    const response = await ai.models.generateContent({
      model: process.env.GEMINI_MODEL || 'gemini-3.6-flash',
      contents: prompt
    });

    let jsonStr = response.text;
    if (jsonStr.startsWith('\`\`\`json')) {
      jsonStr = jsonStr.replace(/^\`\`\`json/, '').replace(/\`\`\`$/, '').trim();
    }
    const resultJSON = JSON.parse(jsonStr);

    // 7. Save Recommendation & Update Task
    const dataFingerprint = crypto.createHash('sha256').update(JSON.stringify(simulation.plan)).digest('hex');

    await prisma.basePrisma.$transaction([
      prisma.basePrisma.irisRecommendation.create({
        data: {
          taskId: task.id,
          type: resultJSON.type,
          evidence: resultJSON.evidence,
          recommendedAction: resultJSON.recommendedAction,
          actionType: resultJSON.actionType,
          actionParameters: resultJSON.actionParameters,
          dataFingerprint,
          expiresAt: simulation.expiresAt
        }
      }),
      prisma.basePrisma.irisTask.update({
        where: { id: task.id },
        data: { status: 'AWAITING_APPROVAL' }
      })
    ]);
    // Emit a Socket.IO event here to notify connected clients instantly
    if (global.io) {
      global.io.to(`tenant:${task.tenantId}:admin`).emit('iris:proactive_alert', {
        taskId: task.id,
        title: "Iris Detected a Shortage",
        message: resultJSON.evidence.summary,
        url: `/dashboard/iris-action/${task.id}`
      });
      global.io.to(`tenant:${task.tenantId}`).emit('inbox:updated', { message: 'New Iris Action Required' });
    }  } catch (error) {
    console.error('Iris Analysis Error:', error);
    await prisma.basePrisma.irisTask.update({
      where: { id: taskId },
      data: { status: 'FAILED' }
    });
  }
}

module.exports = {
  runIrisAnalysis
};
