const prisma = require('../config/db');
const { gatherUserMetrics } = require('../utils/attritionMetrics');
const { computeAttritionRisk } = require('../utils/attritionRiskEngine');
const geminiClient = require('./geminiClient');

async function explainRiskScore(userId, tenantId) {
  const user = await prisma.user.findUnique({
    where: { id: userId, tenantId },
    select: { id: true, displayName: true, dateOfJoining: true, attritionRiskScore: true, attritionRiskLabel: true }
  });

  if (!user) throw new Error('User not found');
  if (user.attritionRiskScore == null) throw new Error('User has no risk score to explain');

  // Fetch the authoritative inputs used by the engine
  const metrics = await gatherUserMetrics(prisma.basePrisma, tenantId, userId, user.dateOfJoining);

  const prompt = `You are an HR AI Assistant for Crew.
Your task is to explain a predictive Attrition Risk score that was generated by the internal Risk Engine.
DO NOT recalculate the score. DO NOT make final HR decisions. DO NOT invent evidence.

AUTHORITATIVE ENGINE OUTPUTS:
Employee: ${user.displayName}
Risk Score: ${user.attritionRiskScore} (Label: ${user.attritionRiskLabel})
Engine Underlying Factors Checked:
- Has enough history (>90 days): ${metrics.hasEnoughHistory}
- Recent Avg Extra Hours: ${metrics.recentAvgExtraHours.toFixed(1)} (Baseline: ${metrics.baselineAvgExtraHours.toFixed(1)})
- Recent Check-in Variance (StdDev mins): ${metrics.recentCheckInStdDevMinutes.toFixed(1)} (Baseline: ${metrics.baselineCheckInStdDevMinutes.toFixed(1)})
- Sick or Short-notice leaves in last 3 months: ${metrics.sickOrShortNoticeLeaveCountLast3Months}

Based ONLY on the metrics above, explain why this score is ${user.attritionRiskScore}.
Provide a clear, natural-language explanation in 3 concise bullet points for an HR manager.`;

  const ai = geminiClient.getAI();
  const response = await ai.models.generateContent({
    model: process.env.GEMINI_MODEL || 'gemini-2.5-flash',
    contents: prompt
  });
  
  const responseText = response.text;
  
  return { 
    score: user.attritionRiskScore,
    label: user.attritionRiskLabel,
    explanation: responseText
  };
}

module.exports = { explainRiskScore };
